name: Release candidate

on:
  workflow_dispatch: {}

jobs:
  rc:
    name: Trigger release candidate build
    runs-on: ubuntu-latest
    container: public.ecr.aws/eksctl/eksctl-build:9b3f575ceb1a272a000ca1fbaded0174096a007a
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
        with:
          token: ${{ secrets.EKSCTLBOT_TOKEN }}
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 #v4.0.0
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Setup identity as eksctl-bot
        uses: ./.github/actions/setup-identity
        with:
          token: "${{ secrets.EKSCTLBOT_TOKEN }}"
      - name: Push tag and open PR to default branch
        run: make prepare-release-candidate
